### ISSUE TITLE
panic: encoding alphabet includes duplicate symbols

### ISSUE THREAD

**Issue by itcwc** [KenmyZhang/aliyun-communicate#5]
goroutine 1 [running]:
encoding/base32.NewEncoding(...)
/usr/local/go/src/encoding/base32/base32.go:79
github.com/KenmyZhang/aliyun-communicate/sms-lib.init()
/root/go/pkg/mod/github.com/!kenmy!zhang/aliyun-communicate@v0.0.0-20180308134849-7997edc57454/sms-lib/sms-lib.go:45 +0xf4

**Comment by 1766987395** [comment]
(sms-lib.go:45)

// var encoding = base32.NewEncoding("ybndrfg8ejkmcpqxot1uwisza345h897")

var encoding = base32.StdEncoding
